import fs from 'fs'
import path from 'path'
import * as azdev from 'azure-devops-node-api'
import {
  addAuditLog,
  addOrchestratorEvent,
  dbGet,
  updateBusinessRequestFields,
  withDb
} from '../_lib/requests-db'
import { resolveActorFromRequest } from '../_lib/session-identity'
import {
  appendAssignedToPatch,
  isAssigneeError,
  removeAssignedToPatch,
  resolveAssigneeForAdo
} from '../../../lib/ado/assignment'

const STAGE_NAME = 'stage1-demand-manager'
const defaultInstructionPath = path.join(
  process.cwd(),
  'data',
  'agent-instructions',
  'stage1-demand-manager.md'
)
const adoConfigPath = path.join(process.cwd(), 'public', '.ado-config.json')

function nowIso() {
  return new Date().toISOString()
}

function formatError(err) {
  return String(err?.message || err)
}

async function withTimeout(promiseFactory, timeoutMs, label) {
  let timeoutHandle = null
  const timeoutPromise = new Promise((_, reject) => {
    timeoutHandle = setTimeout(() => {
      reject(new Error(`${label} timed out after ${timeoutMs}ms`))
    }, timeoutMs)
  })

  try {
    return await Promise.race([promiseFactory(), timeoutPromise])
  } finally {
    if (timeoutHandle) clearTimeout(timeoutHandle)
  }
}

function loadInstruction() {
  if (!fs.existsSync(defaultInstructionPath)) {
    return 'Act as a Demand Manager and return valid JSON demand analysis.'
  }
  return fs.readFileSync(defaultInstructionPath, 'utf-8')
}

function loadAdoConfig() {
  if (!fs.existsSync(adoConfigPath)) return null
  try {
    return JSON.parse(fs.readFileSync(adoConfigPath, 'utf-8'))
  } catch {
    return null
  }
}

function extractJsonFromText(text) {
  if (!text || typeof text !== 'string') return null
  const trimmed = text.trim()
  try {
    return JSON.parse(trimmed)
  } catch {
    // fall through
  }

  const first = trimmed.indexOf('{')
  const last = trimmed.lastIndexOf('}')
  if (first >= 0 && last > first) {
    const candidate = trimmed.slice(first, last + 1)
    try {
      return JSON.parse(candidate)
    } catch {
      return null
    }
  }
  return null
}

function unique(items) {
  return Array.from(new Set(items.filter(Boolean)))
}

async function getOllamaModels(baseUrl) {
  try {
    const response = await fetch(`${baseUrl}/api/tags`)
    if (!response.ok) return []
    const data = await response.json()
    const models = Array.isArray(data?.models) ? data.models : []
    return unique(models.map((m) => m.name || m.model).filter(Boolean))
  } catch {
    return []
  }
}

function buildStage1Fallback(br) {
  return {
    demandSummary: `Demand package for ${br.id}`,
    businessProblem: br.description || 'Business request requires analysis',
    objectives: [
      'Clarify core business outcomes and stakeholders',
      'Define phased delivery boundaries and dependencies',
      'Establish baseline budget and timeline'
    ],
    budgetEstimate: { range: br.urgency === 'High' ? '100k - 180k' : '50k - 120k' },
    timelineEstimate: { duration: br.urgency === 'High' ? '8-12 weeks' : '10-16 weeks' },
    deliveryRecommendation: 'Proceed with staged implementation and formal BRD review gate.'
  }
}

async function updateBr(id, fields) {
  await withDb(async (db) => {
    await updateBusinessRequestFields(db, id, fields)
  })
}

async function postDemandToAdo(br, demandOutput) {
  const config = loadAdoConfig()
  const adoTimeoutMs = Number(process.env.ADO_TIMEOUT_MS || 15000)
  if (!config?.organization || !config?.project || !config?.pat) {
    return { skipped: true, reason: 'ADO is not configured' }
  }

  let witApi = null
  try {
    const authHandler = azdev.getPersonalAccessTokenHandler(config.pat)
    const connection = new azdev.WebApi(`https://dev.azure.com/${config.organization}`, authHandler)
    witApi = await withTimeout(
      () => connection.getWorkItemTrackingApi(),
      adoTimeoutMs,
      'ADO API connection'
    )
  } catch (err) {
    return {
      skipped: true,
      reason: `ADO unavailable: ${formatError(err)}`
    }
  }

  const summary = demandOutput?.demandSummary || 'Demand analysis generated by Stage 1'
  const recommendation = demandOutput?.deliveryRecommendation || 'N/A'
  const objectives = Array.isArray(demandOutput?.objectives)
    ? demandOutput.objectives.map((x) => `<li>${String(x)}</li>`).join('')
    : ''

  const description = [
    `<p><strong>BR ID:</strong> ${br.id}</p>`,
    `<p><strong>Business Problem:</strong> ${demandOutput?.businessProblem || br.description || 'N/A'}</p>`,
    `<p><strong>Demand Summary:</strong> ${summary}</p>`,
    objectives ? `<p><strong>Objectives:</strong></p><ul>${objectives}</ul>` : '',
    `<p><strong>Budget Estimate:</strong> ${demandOutput?.budgetEstimate?.range || 'TBD'}</p>`,
    `<p><strong>Timeline:</strong> ${demandOutput?.timelineEstimate?.duration || 'TBD'}</p>`,
    `<p><strong>Delivery Recommendation:</strong> ${recommendation}</p>`
  ].filter(Boolean).join('')

  const workItemPatch = [
    { op: 'add', path: '/fields/System.Title', value: `[Demand] ${br.id} - ${summary.slice(0, 110)}` },
    { op: 'add', path: '/fields/System.Description', value: description },
    { op: 'add', path: '/fields/System.Tags', value: 'Demand;AI-Orchestrator;Stage1' }
  ]
  const assignedTo = await resolveAssigneeForAdo({ config })
  const workItemPatchWithAssignee = appendAssignedToPatch(workItemPatch, assignedTo)

  // Prefer Issue, fallback to Task for templates that don't include Issue.
  try {
    const issue = await withTimeout(
      () => witApi.createWorkItem(null, workItemPatchWithAssignee, config.project, 'Issue'),
      adoTimeoutMs,
      'ADO Issue creation'
    )
    return {
      skipped: false,
      workItemId: issue?.id || null,
      url: issue?.id
        ? `https://dev.azure.com/${config.organization}/${config.project}/_workitems/edit/${issue.id}`
        : null,
      workItemType: 'Issue'
    }
  } catch (issueErr) {
    const patchWithoutAssignee = removeAssignedToPatch(workItemPatchWithAssignee)
    const canRetryWithoutAssignee = assignedTo && isAssigneeError(issueErr)

    if (canRetryWithoutAssignee) {
      try {
        const issueWithoutAssignee = await withTimeout(
          () => witApi.createWorkItem(null, patchWithoutAssignee, config.project, 'Issue'),
          adoTimeoutMs,
          'ADO Issue creation (without assignee)'
        )
        return {
          skipped: false,
          workItemId: issueWithoutAssignee?.id || null,
          url: issueWithoutAssignee?.id
            ? `https://dev.azure.com/${config.organization}/${config.project}/_workitems/edit/${issueWithoutAssignee.id}`
            : null,
          workItemType: 'Issue'
        }
      } catch {
        // Continue to Task fallback.
      }
    }

    try {
      const task = await withTimeout(
        () => witApi.createWorkItem(null, workItemPatchWithAssignee, config.project, 'Task'),
        adoTimeoutMs,
        'ADO Task creation'
      )
      return {
        skipped: false,
        workItemId: task?.id || null,
        url: task?.id
          ? `https://dev.azure.com/${config.organization}/${config.project}/_workitems/edit/${task.id}`
          : null,
        workItemType: 'Task'
      }
    } catch (taskErr) {
      if (assignedTo && isAssigneeError(taskErr)) {
        try {
          const taskWithoutAssignee = await withTimeout(
            () => witApi.createWorkItem(null, patchWithoutAssignee, config.project, 'Task'),
            adoTimeoutMs,
            'ADO Task creation (without assignee)'
          )
          return {
            skipped: false,
            workItemId: taskWithoutAssignee?.id || null,
            url: taskWithoutAssignee?.id
              ? `https://dev.azure.com/${config.organization}/${config.project}/_workitems/edit/${taskWithoutAssignee.id}`
              : null,
            workItemType: 'Task'
          }
        } catch {
          // Fall through to unified failure message.
        }
      }

      return {
        skipped: true,
        reason: `ADO create failed: ${formatError(issueErr)} | ${formatError(taskErr)}`
      }
    }
  }
}

async function runDemandAnalysis({ model, prompt, br }) {
  const baseUrl = process.env.OLLAMA_BASE_URL || 'http://127.0.0.1:11434'
  const modelTimeoutMs = Number(process.env.OLLAMA_MODEL_TIMEOUT_MS || 45000)
  const maxModelAttempts = Number(process.env.OLLAMA_MAX_MODEL_ATTEMPTS || 3)
  const available = await getOllamaModels(baseUrl)
  const envFallbacks = String(process.env.OLLAMA_MODEL_FALLBACKS || '')
    .split(',')
    .map((x) => x.trim())
    .filter(Boolean)
  const preferredCandidates = unique([
    model,
    process.env.OLLAMA_MODEL_STAGE1,
    process.env.OLLAMA_MODEL,
    ...envFallbacks,
    'qwen3:4b',
    'qwen3:8b',
    'llama3.1',
    'llama3'
  ])

  const candidates = available.length > 0
    ? unique([...preferredCandidates.filter((x) => available.includes(x)), ...available])
    : preferredCandidates

  let lastError = ''
  for (const candidateModel of candidates.slice(0, maxModelAttempts)) {
    const controller = new AbortController()
    const timeoutHandle = setTimeout(() => controller.abort(), modelTimeoutMs)

    let response = null
    try {
      response = await fetch(`${baseUrl}/api/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: candidateModel,
          prompt,
          stream: false,
          options: { temperature: 0.2 }
        }),
        signal: controller.signal
      })
    } catch (err) {
      const isTimeout = err && err.name === 'AbortError'
      lastError = isTimeout
        ? `Timed out after ${modelTimeoutMs}ms for model ${candidateModel}`
        : String(err?.message || err)
      clearTimeout(timeoutHandle)
      continue
    }

    clearTimeout(timeoutHandle)

    const text = await response.text()
    let parsed = null
    try {
      parsed = text ? JSON.parse(text) : null
    } catch {
      parsed = null
    }

    if (!response.ok) {
      lastError = parsed?.error || parsed?.message || text || `OLLAMA error (${response.status})`
      continue
    }

    if (!parsed?.response) {
      lastError = 'OLLAMA response did not contain generated content'
      continue
    }

    return {
      text: parsed.response,
      modelUsed: candidateModel,
      source: 'ollama',
      warning: null
    }
  }

  return {
    text: JSON.stringify(buildStage1Fallback(br), null, 2),
    modelUsed: 'template-fallback',
    source: 'fallback-template',
    warning: lastError || 'No working OLLAMA model found'
  }
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' })
  }

  const { id } = req.body || {}
  const actor = resolveActorFromRequest(req, req.body && req.body.actor, 'Workflow Operator')
  const model = (req.body && req.body.model) || process.env.OLLAMA_MODEL_STAGE1 || process.env.OLLAMA_MODEL || 'llama3.1'

  if (!id) {
    return res.status(400).json({ message: 'Missing id' })
  }

  let br = null
  try {
    br = await withDb(async (db) => {
      return dbGet(db, 'SELECT * FROM business_requests WHERE id = ?', [id])
    })

    if (!br) {
      return res.status(404).json({ message: 'Business request not found' })
    }

    const status = String(br.status || '').toLowerCase()
    if (status !== 'approved') {
      return res.status(400).json({ message: 'Stage 1 can run only for approved business requests' })
    }

    await updateBr(id, {
      stage1_status: 'Running',
      stage1_error: null,
      stage1_model: model
    })

    await addOrchestratorEvent({
      brId: id,
      stage: STAGE_NAME,
      eventType: 'info',
      message: 'Stage 1 started',
      payload: { model, actor }
    })

    await addAuditLog({
      brId: id,
      stage: 'Stage 1 Demand Analysis',
      actor,
      action: 'Stage 1 started',
      details: { model }
    })

    const instruction = loadInstruction()
    const prompt = [
      instruction,
      '',
      'Business Request Input:',
      JSON.stringify(
        {
          id: br.id,
          description: br.description,
          businessUnit: br.unit,
          urgency: br.urgency,
          date: br.date,
          justification: br.justif,
          status: br.status
        },
        null,
        2
      )
    ].join('\n')

    await addOrchestratorEvent({
      brId: id,
      stage: STAGE_NAME,
      eventType: 'info',
      message: 'Sending instruction prompt to OLLAMA',
      payload: { model }
    })

    const aiTotalTimeoutMs = Number(process.env.OLLAMA_TOTAL_TIMEOUT_MS || 120000)
    let aiResult = null
    try {
      aiResult = await withTimeout(
        () => runDemandAnalysis({ model, prompt, br }),
        aiTotalTimeoutMs,
        'Stage 1 AI generation'
      )
    } catch (err) {
      aiResult = {
        text: JSON.stringify(buildStage1Fallback(br), null, 2),
        modelUsed: 'guard-timeout-fallback',
        source: 'guard-timeout-fallback',
        warning: formatError(err)
      }
    }
    const parsedOutput = extractJsonFromText(aiResult.text)
    const stage1Output = parsedOutput || { raw: aiResult.text }

    await addOrchestratorEvent({
      brId: id,
      stage: STAGE_NAME,
      eventType: 'info',
      message: 'OLLAMA response received and parsed',
      payload: {
        parsedAsJson: Boolean(parsedOutput),
        modelUsed: aiResult.modelUsed,
        source: aiResult.source,
        warning: aiResult.warning
      }
    })

    const completedAt = nowIso()
    let adoResult = null

    try {
      adoResult = await postDemandToAdo(br, stage1Output)
      if (adoResult?.skipped) {
        await addOrchestratorEvent({
          brId: id,
          stage: STAGE_NAME,
          eventType: 'warning',
          message: 'ADO sync skipped for Stage 1',
          payload: adoResult
        })
      } else {
        await addOrchestratorEvent({
          brId: id,
          stage: STAGE_NAME,
          eventType: 'info',
          message: 'Stage 1 output posted to ADO',
          payload: adoResult
        })
      }
    } catch (adoError) {
      adoResult = {
        skipped: true,
        reason: `ADO post failed: ${String(adoError.message || adoError)}`
      }
      await addOrchestratorEvent({
        brId: id,
        stage: STAGE_NAME,
        eventType: 'warning',
        message: 'ADO sync failed for Stage 1',
        payload: adoResult
      })
    }

    await updateBr(id, {
      stage1_status: 'Completed',
      stage1_output: JSON.stringify(stage1Output),
      stage1_error: null,
      stage1_completed_at: completedAt,
      stage1_ado_work_item_id: adoResult?.workItemId ? String(adoResult.workItemId) : null,
      stage1_model: aiResult.modelUsed
    })

    await addOrchestratorEvent({
      brId: id,
      stage: STAGE_NAME,
      eventType: 'success',
      message: 'Stage 1 completed successfully',
      payload: {
        completedAt,
        adoWorkItemId: adoResult?.workItemId || null,
        actor
      }
    })

    await addAuditLog({
      brId: id,
      stage: 'Stage 1 Demand Analysis',
      actor,
      action: 'Stage 1 completed',
      details: {
        completedAt,
        adoWorkItemId: adoResult?.workItemId || null,
        modelRequested: model,
        modelUsed: aiResult.modelUsed,
        source: aiResult.source,
        warning: aiResult.warning
      }
    })

    return res.status(200).json({
      success: true,
      stage: 'Stage 1',
      model: aiResult.modelUsed,
      output: stage1Output,
      ado: adoResult
    })
  } catch (err) {
    const message = String(err.message || err)
    try {
      await updateBr(id, {
        stage1_status: 'Failed',
        stage1_error: message
      })
      await addOrchestratorEvent({
        brId: id,
        stage: STAGE_NAME,
        eventType: 'error',
        message: 'Stage 1 failed',
        payload: { error: message, actor }
      })

      await addAuditLog({
        brId: id,
        stage: 'Stage 1 Demand Analysis',
        actor,
        action: 'Stage 1 failed',
        details: { error: message, model }
      })
    } catch (secondaryError) {
      console.error('Failed to persist Stage 1 error', secondaryError)
    }

    return res.status(500).json({
      message: 'Stage 1 failed',
      error: message
    })
  }
}
